CREATE TABLE IF NOT EXISTS authors (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT
);
